### ISSUE TITLE
union with list after String/String16 is not supported

### ISSUE THREAD

**Issue by Anisotrop** [reaktivity/nukleus-maven-plugin#40]
Change `test.idl` to add a list like the following:

```
union UnionOctets switch (uint8)
        {
            case 1: octets[4] octets4;
            case 2: octets[16] octets16;
            case 3: string string1;
            case 4: list<string> list1;
        }
```

Running `mvn clean install` yelds:
```
[INFO] --- exec-maven-plugin:1.6.0:java (default) @ nukleus-maven-plugin ---
line 62:20 no viable alternative at input 'list'
Parse failed in test.idl at 62:20 on "list"
[WARNING] 
org.antlr.v4.runtime.misc.ParseCancellationException
        at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:51)
        at org.reaktivity.nukleus.maven.plugin.internal.parser.NukleusParser.member(NukleusParser.java:2167)
        at org.reaktivity.nukleus.maven.plugin.internal.parser.NukleusParser.case_member(NukleusParser.java:2624)
        [...]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.antlr.v4.runtime.NoViableAltException
        at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2023)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
        at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
        at org.reaktivity.nukleus.maven.plugin.internal.parser.NukleusParser.member(NukleusParser.java:2132)
        ... 21 more
```

Could try to add `unbounded_list_type` to `constr_type_spec` in `Nukleus.g4`:
```
constr_type_spec
   : enum_type
   | struct_type
   | union_type
   | unbounded_list_type
   ;
```

The exception is no longer thrown, but it generates code that doesn’t compile. The new call and the 2 added methods are:

```java
public Builder string1(String value) {
      if (value == null) {
        limit(offset() + FIELD_OFFSET_STRING1);
      } else {
        kind(KIND_STRING1);
        StringFW.Builder string1 = string1();
        string1.set(value, StandardCharsets.UTF_8);
        list1(string1.build().limit()); // <--------------------new call
        limit(string1.build().limit());
      }
      return this;
    }

    private ListFW.Builder<StringFW.Builder, StringFW> list1(int offset) {
      return list1RW.wrap(buffer(), offset, maxLimit());
    }

    public Builder list1(Consumer<StringFW.Builder> mutator) {
      kind(KIND_LIST1);
      list1().item(mutator); // <------------------ method does not exist
      super.limit(list1RW.limit());
      return this;
    }
```

**Comment by jfallows** [comment]
@Anisotrop is this issue now resolved by #39 ?

**Comment by Anisotrop** [comment]
Hello @jfallows I am still seeing the same behavior. Getting passed the `ParseCancellationException` by changing the .g4 the following error appears:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] ~/reaktivity/nukleus-maven-plugin/target/generated-test-sources/test-reaktivity/org/reaktivity/reaktor/internal/test/types/inner/UnionOctetsFW.java:[208,7] no suitable method found for list1(no arguments)
    method org.reaktivity.reaktor.internal.test.types.inner.UnionOctetsFW.Builder.list1(int) is not applicable
      (actual and formal argument lists differ in length)
    method org.reaktivity.reaktor.internal.test.types.inner.UnionOctetsFW.Builder.list1(java.util.function.Consumer<org.reaktivity.reaktor.internal.test.types.StringFW.Builder>) is not applicable
      (actual and formal argument lists differ in length)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.219 s
[INFO] Finished at: 2017-12-18T11:58:52+02:00
[INFO] Final Memory: 38M/382M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project nukleus-maven-plugin: Compilation failure
[ERROR] ~/reaktivity/nukleus-maven-plugin/target/generated-test-sources/test-reaktivity/org/reaktivity/reaktor/internal/test/types/inner/UnionOctetsFW.java:[208,7] no suitable method found for list1(no arguments)
[ERROR]     method org.reaktivity.reaktor.internal.test.types.inner.UnionOctetsFW.Builder.list1(int) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
[ERROR]     method org.reaktivity.reaktor.internal.test.types.inner.UnionOctetsFW.Builder.list1(java.util.function.Consumer<org.reaktivity.reaktor.internal.test.types.StringFW.Builder>) is not applicable
[ERROR]       (actual and formal argument lists differ in length)
```

The changes are:
```patch
diff --git a/src/main/antlr4/org/reaktivity/nukleus/maven/plugin/internal/parser/Nukleus.g4 b/src/main/antlr4/org/reaktivity/nukleus/maven/plugin/internal/parser/Nukleus.g4
index d889b74..d9989ab 100644
--- a/src/main/antlr4/org/reaktivity/nukleus/maven/plugin/internal/parser/Nukleus.g4
+++ b/src/main/antlr4/org/reaktivity/nukleus/maven/plugin/internal/parser/Nukleus.g4
@@ -74,6 +74,7 @@ constr_type_spec
    : enum_type
    | struct_type
    | union_type
+   | unbounded_list_type
    ;

 declarators
diff --git a/src/test/resources/test-project/test.idl b/src/test/resources/test-project/test.idl
index 140b6e3..f3bf5e9 100644
--- a/src/test/resources/test-project/test.idl
+++ b/src/test/resources/test-project/test.idl
@@ -65,6 +65,7 @@ scope test
             case 1: octets[4] octets4;
             case 2: octets[16] octets16;
             case 3: string string1;
+            case 4: list<string> list1;
         }

         struct Integers
~                            
```
The branch is `develop` on my [fork](https://github.com/anisotrop/nukleus-maven-plugin):
```
$ git log
commit 151d7e72a15dfb48177becac00987630f57663d2
Merge: cadd241 736e51c
Author: John Fallows <john.fallows@kaazing.com>
Date:   Thu Dec 14 15:12:36 2017 -0800

    Merge tag '0.22' into develop
    
    0.22 0.22
```
